
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]

title : Welcome. Here's a website.
author :
  name : John Li
  email : johnmarkli@gmail.com
  github : johnmarkli
